"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s9rcyZCzOQbx8fAompkhLP4EG1om5z1o
"""

print("Hello world !")

if 5 > 2:
  print("Five is greater than two!")

if 5 > 2:
  print("Five is greater than two !")

if 5 > 2:
  print("Five is greater than two !")
if 5 > 2:
  print("Five is greater than two !")

if 5 > 2:
  print("Five is greater than two!")
         print("Five is greater than two!")

thislist = ["apple","banana","cherry"]
print(thislist)

thislist = ["apple","banana","cherry","apple","cherry"]
print(thislist)

thislist = ["apple","banana","cherry"]
print(thislist[1])

thislist = ["apple","banana","cherry","orange","kiwi","melon","mango"]
print(thislist[2:5])

thistuple = ("apple","banana","cherry")
print(thistuple)

thisset = ("apple","banana","cherry")
print(thisset)

class MyClass:
  x = 5

p1 = MyClass()
print(p1.x)

class Person:
  def __init__(self,name,age):
    self.name = name
    self.age = age

p1 = Person("john",36)

print(p1.name)
print(p1.age)

class point:
  def __init__(self, x = 0 ,y = 0):
    self.x = x
    self.y = y


  def add_points(self,other):
    x = self.x + other.x
    y = self.y + other.y
    return point(x,y)

p1 = point(1,2)
p2 = point(2,3)

p3 = p1.add_points(p2)


print((p3.x, p3.y))

class Person:
  def __init__(self,name,age):
    self.name = name
    self.age = age
  def __lt__(self, other):
    return self.age < other.age

p1 = Person("Alice",20)
p2 = Person("Bob",30)

print(p1<p2)
print(p2<p1)

"""# New Section"""

x = divmod(5,2)

print(x)

















